plugins {
    id 'java'
}

tasks.register('run', JavaExec) {
    group = "application"
    description = "Run the main class"
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'battleships.Main'
    standardInput = System.in
}

group = 'battleships'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation('com.fasterxml.uuid:java-uuid-generator:5.0.0')
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}